### ISSUE TITLE
 Cannot declare class qivivoAPI, because the name is already in use 

### ISSUE THREAD

**Issue by dedelajoie** [KiboOst/php-qivivoAPI#1]
Hello 

I used to be a real fan of your previous achievment with Qivivo and I was delighted to realize you already had released a new version. Unfortunately I cannot manage to get this one work. The error I came accross is way beyond my ability to correct it in php.

php version is : PHP 7.4.10

here is the file I tried to get to work (I just omited the php tags at the beginning and the end )

```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
// require_once('qivivoAPI.php');
echo "1";
$qivivo_user="XXXXXXXXXXXXXXX";
$qivivo_pass="XXXXXXXXXXX";
require($_SERVER['DOCUMENT_ROOT'].'/qivivoAPIv2.php');
echo "2";
$_qivivo = new qivivoAPI($qivivo_user, $qivivo_pass);
if (isset($_qivivo->error)) echo $_qivivo->error;
echo "fini";
```

I tried with and without including the line : 
`require_once('qivivoAPI.php');`

but I always get the same php error which is : 
```
Fatal error: Cannot declare class qivivoAPI, because the name is already in use in /var/www/html/qivivoAPIv2.php on line 8
```

thank you

**Comment by KiboOst** [comment]
Hi,
You can trash the old api qivivoAPI.php and splQivivoAPI.php they don't and won't work anymore.
qivivoAPI.php and qivivoAPIv2.php have same class name so indeed you can't include the two.
You error message means you imported the old one before importing the new one, so the class name is already define and can't be imported/declared another time.

**Comment by dedelajoie** [comment]
how stupid me ! 
merci beaucoup cher compatriote
