### ISSUE TITLE
"authentification error" when calling "qivivoAPIv2.php"

### ISSUE THREAD

**Issue by dedelajoie** [KiboOst/php-qivivoAPI#2]
hello, 

I cannot get my previous php program to work. I receive an "authentification error" when I run the following code : 

----------------------
$qivivo_user="mail@mail.me";
$qivivo_pass="************";
require($_SERVER['DOCUMENT_ROOT'].'/qivivoAPIv2.php');
$_qivivo = new qivivoAPI($qivivo_user, $qivivo_pass);
if (isset($_qivivo->error)) echo $_qivivo->error;
------------------------

my php version is : 
PHP 7.4.3

needless to say that I checked the login and password (I even changed it to make sure it wasn't a mistake on may own)

Is there anything that might have change since last year ? (especially since they upgraded their platform)

thank you for your wonderful work, a true fan !

**Comment by KiboOst** [comment]
Sorry, working mainly on Jeedom plugin and didn't updated this repo.

The api file is now comapAPI.php, please try it and let me know if all works again ,-)

**Comment by dedelajoie** [comment]
It works ! 
thank you again for this great piece of work ! 
anyway to say thank you ? 

![image](https://user-images.githubusercontent.com/33811121/136251968-14f0db28-e42c-4cbf-8d83-a2709f8889b7.png)

**Comment by dedelajoie** [comment]
thank you again for your great work !
